<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Matias Saforas Gomez · Portafolio Base de Datos II</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Sora:wght@300;400;600;800&display=swap" rel="stylesheet">
<style>
:root{--teal:#4D7C8A;--lime:#CBDF90;--blue:#1B4079;--sage:#8FAD88;--dark:#070B10;--dark2:#0B121A;--panel:#0F1922;--panel2:#141F28;--border:rgba(77,124,138,.32);--text:#E8F0EC;--muted:#8AA1A5;--danger:#d0604c}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{background:var(--dark);color:var(--text);font-family:Sora,sans-serif;min-height:100vh;overflow-x:hidden}body:before{content:"";position:fixed;inset:0;background-image:linear-gradient(rgba(77,124,138,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(77,124,138,.035) 1px,transparent 1px);background-size:36px 36px;pointer-events:none}h1,h2,h3{letter-spacing:0}button,input{font:inherit}button{cursor:pointer}
#login-screen{min-height:100vh;display:grid;place-items:center;padding:24px;position:relative;z-index:10}.login-card{width:min(440px,100%);background:var(--panel);border:1px solid var(--border);box-shadow:0 28px 80px rgba(0,0,0,.55)}.login-bar{height:42px;background:var(--panel2);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:8px;padding:0 15px}.dot{width:10px;height:10px;border-radius:50%}.red{background:#d0604c}.yellow{background:#d9ac45}.green{background:var(--sage)}.login-bar b{font:700 .7rem 'Space Mono';color:var(--muted);margin-left:7px}.login-body{padding:38px}.login-icon{width:58px;height:58px;border:1px solid var(--teal);display:grid;place-items:center;margin:0 auto 24px;color:var(--lime);font-size:1.6rem}.login-title{text-align:center;font-size:1.55rem}.login-sub,.login-foot{text-align:center;color:var(--muted);font-size:.78rem;margin-top:9px}.login-form{display:grid;gap:15px;margin-top:28px}label{display:block;color:var(--muted);font:700 .7rem 'Space Mono';text-transform:uppercase;margin-bottom:7px}input{width:100%;background:var(--dark2);border:1px solid var(--border);color:var(--text);padding:12px 14px;outline:none}input:focus{border-color:var(--lime)}.login-submit{padding:13px;border:0;background:var(--lime);color:var(--dark);font-weight:800}.login-error{display:none;color:#ff8b7b;font-size:.76rem;text-align:center}.hint{font-size:.7rem;color:var(--muted);text-align:center;margin-top:15px}
#app-screen{display:none;position:relative;z-index:1}nav{position:sticky;top:0;z-index:20;height:68px;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(18px,4vw,56px);background:rgba(7,11,16,.92);backdrop-filter:blur(12px);border-bottom:1px solid var(--border)}.nav-brand{font:700 .72rem 'Space Mono';color:var(--lime);line-height:1.45;text-transform:uppercase}.nav-links{display:flex;align-items:center;gap:24px;list-style:none}.nav-links a{font:700 .68rem 'Space Mono';color:var(--muted);text-decoration:none;text-transform:uppercase}.nav-links a:hover{color:var(--lime)}.logout{border:1px solid var(--border);background:transparent;color:var(--text);padding:8px 12px;font-size:.72rem}
.hero{min-height:calc(100vh - 68px);display:grid;place-items:center;padding:70px 24px 54px;border-bottom:1px solid var(--border)}.hero-inner{max-width:920px;text-align:center}.eyebrow,.section-label{font:700 .73rem 'Space Mono';color:var(--lime);text-transform:uppercase;letter-spacing:.08em}.hero-name{font-size:clamp(2.8rem,8vw,6.5rem);line-height:.94;margin:22px 0;color:var(--text)}.hero-name span{color:var(--lime)}.hero-desc{max-width:720px;margin:auto;color:var(--muted);line-height:1.85}.profile-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--border);border:1px solid var(--border);margin-top:38px;text-align:left}.profile-grid div{background:var(--panel);padding:18px}.profile-grid small{display:block;font:700 .64rem 'Space Mono';color:var(--teal);text-transform:uppercase;margin-bottom:6px}.profile-grid strong{font-size:.84rem}
main section{padding:90px clamp(18px,6vw,90px);max-width:1250px;margin:auto}.section-title{font-size:clamp(2rem,4vw,3.3rem);margin:10px 0 34px}.codex-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.codex-card,.week-card,.question-card{background:var(--panel);border:1px solid var(--border);padding:24px}.codex-card span{font:700 .7rem 'Space Mono';color:var(--teal)}.codex-card h3{font-size:1rem;margin:25px 0 10px;color:var(--lime)}.codex-card p,.week-card p,.question-card p{color:var(--muted);font-size:.84rem;line-height:1.7}
#unidades{max-width:none;background:var(--dark2);border-block:1px solid var(--border)}#unidades>.inner{max-width:1120px;margin:auto}.unit-tabs{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:24px}.unit-tab{border:1px solid var(--border);background:var(--panel);color:var(--muted);padding:12px 18px;font:700 .72rem 'Space Mono'}.unit-tab.active{background:var(--teal);color:var(--text)}.unit-tab.locked{opacity:.45}.unit-panel{display:none}.unit-panel.active{display:block}.capacity{border-left:3px solid var(--lime);background:var(--panel);padding:18px;color:var(--muted);line-height:1.65;margin-bottom:18px}.weeks-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.week-card{position:relative}.week-num{font:700 .7rem 'Space Mono';color:var(--lime)}.week-card h3{font-size:1.06rem;margin:12px 0}.progress{height:4px;background:var(--dark);margin:22px 0 8px}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--teal),var(--lime))}.week-card small{font:400 .65rem 'Space Mono';color:var(--muted)}
.questions-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.question-card{display:grid;grid-template-columns:44px 1fr;gap:14px;transition:.2s}.question-card:hover{border-color:var(--lime);transform:translateY(-2px)}.q-number{font:700 .72rem 'Space Mono';color:var(--lime);border-right:1px solid var(--border);padding-top:3px}.question-card h3{font-size:.96rem;margin-bottom:9px}footer{padding:35px 20px;text-align:center;border-top:1px solid var(--border);color:var(--muted);font-size:.75rem}
.bot-toggle{position:fixed;right:22px;bottom:22px;z-index:30;width:52px;height:52px;border:0;background:var(--lime);color:var(--dark);font-size:1.25rem;box-shadow:0 12px 35px rgba(0,0,0,.4)}.bot-panel{display:none;position:fixed;right:22px;bottom:84px;z-index:30;width:min(360px,calc(100vw - 28px));background:var(--panel);border:1px solid var(--border);box-shadow:0 20px 60px rgba(0,0,0,.6)}.bot-panel.open{display:block}.bot-head{padding:14px 16px;border-bottom:1px solid var(--border);display:flex;justify-content:space-between}.bot-messages{height:230px;overflow:auto;padding:15px;display:grid;gap:10px}.msg{padding:10px;background:var(--dark2);font-size:.78rem;line-height:1.5}.bot-form{display:flex;border-top:1px solid var(--border)}.bot-form input{border:0}.bot-form button{width:48px;border:0;background:var(--teal);color:var(--text)}
@media(max-width:800px){nav{height:auto;padding:14px 18px;align-items:flex-start}.nav-links{gap:10px;flex-wrap:wrap;justify-content:flex-end}.nav-links a{font-size:.58rem}.profile-grid,.codex-grid,.weeks-grid,.questions-grid{grid-template-columns:1fr 1fr}.hero{min-height:auto}}
@media(max-width:560px){.nav-brand{display:none}nav{justify-content:center}.profile-grid,.codex-grid,.weeks-grid,.questions-grid{grid-template-columns:1fr}main section{padding-block:65px}.question-card{grid-template-columns:34px 1fr}}
.card-pdf-thumb{width:100%;height:110px;background:#0D0D15;border:1px solid rgba(255,255,255,.08);border-radius:6px;display:flex;align-items:center;justify-content:center;overflow:hidden;position:relative;margin:14px 0;cursor:pointer}
.card-pdf-thumb canvas{max-width:100%;max-height:100%;object-fit:contain;border-radius:4px}
.card-pdf-thumb .thumb-placeholder{display:flex;flex-direction:column;align-items:center;gap:8px;color:var(--muted);font:400 .68rem 'Space Mono';text-transform:uppercase;letter-spacing:.06em}
.card-pdf-thumb .thumb-placeholder svg{width:30px;height:30px;opacity:.4}
.card-pdf-thumb:hover .thumb-placeholder{color:var(--lime)}
.card-actions{display:flex;gap:8px;align-items:center;margin-top:10px}
.preview-btn{display:inline-flex;align-items:center;gap:7px;padding:10px 14px;background:var(--teal);border:1px solid var(--teal);color:#fff;border-radius:6px;font:700 .68rem 'Space Mono';letter-spacing:.05em;text-transform:uppercase;cursor:pointer;text-decoration:none;transition:.2s;flex:1;justify-content:center}
.preview-btn:hover{filter:brightness(1.15)}
.download-btn{display:inline-flex;align-items:center;justify-content:center;padding:10px 13px;background:transparent;border:1px solid var(--teal);color:var(--teal);border-radius:6px;cursor:pointer;text-decoration:none;transition:.2s}
.download-btn:hover{background:var(--teal);color:#fff}
.download-btn svg,.preview-btn svg{width:13px;height:13px;fill:currentColor;flex-shrink:0}
.questions-btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;margin-top:12px;padding:11px 14px;background:transparent;border:1px dashed var(--lime);color:var(--lime);border-radius:6px;font:700 .68rem 'Space Mono';letter-spacing:.05em;text-transform:uppercase;cursor:pointer;transition:.2s}
.questions-btn:hover{background:rgba(203,223,144,.1)}
.questions-panel{display:none;grid-column:1/-1;background:var(--panel);border:1px solid var(--border);border-top:3px solid var(--lime);padding:26px;margin-top:14px}
.questions-panel.open{display:block}
.questions-panel-head{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;margin-bottom:20px}
.questions-panel-head h3{font-size:1.15rem;color:var(--lime)}
.questions-panel-head span{font:400 .72rem 'Space Mono';color:var(--muted)}
.questions-close{border:1px solid var(--border);background:transparent;color:var(--text);padding:8px 14px;font:700 .68rem 'Space Mono';text-transform:uppercase;letter-spacing:.05em}
.questions-close:hover{border-color:var(--lime);color:var(--lime)}
.pdf-modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,.85);backdrop-filter:blur(8px);z-index:999;display:flex;align-items:center;justify-content:center;opacity:0;pointer-events:none;transition:opacity .3s ease}
.pdf-modal-overlay.open{opacity:1;pointer-events:all}
.pdf-modal{background:#0F1922;border:1px solid var(--border);border-radius:14px;width:95vw;max-width:1050px;height:88vh;display:flex;flex-direction:column;overflow:hidden;transform:translateY(20px) scale(.97);transition:transform .3s ease;box-shadow:0 40px 100px rgba(0,0,0,.7)}
.pdf-modal-overlay.open .pdf-modal{transform:translateY(0) scale(1)}
.pdf-modal-header{background:var(--panel2);border-bottom:1px solid var(--border);padding:14px 20px;display:flex;align-items:center;gap:14px;flex-shrink:0}
.pdf-modal-folder{font-size:.9rem;font-weight:700;color:var(--text)}
.pdf-modal-subtitle{font:400 .7rem 'Space Mono';color:var(--muted);margin-top:2px}
.pdf-modal-close{margin-left:auto;background:rgba(255,255,255,.06);border:1px solid var(--border);color:var(--muted);width:32px;height:32px;border-radius:8px;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:1.05rem;flex-shrink:0}
.pdf-modal-close:hover{background:var(--teal);color:#fff}
.pdf-modal-body{display:flex;flex:1;overflow:hidden}
.pdf-sidebar{width:170px;flex-shrink:0;background:var(--dark2);border-right:1px solid var(--border);overflow-y:auto;padding:12px 8px;display:flex;flex-direction:column;gap:8px}
.pdf-thumb-item{cursor:pointer;border-radius:6px;overflow:hidden;border:2px solid transparent;background:var(--panel2);display:flex;flex-direction:column;align-items:center;padding:6px 6px 5px;gap:5px}
.pdf-thumb-item:hover{border-color:rgba(77,124,138,.5)}
.pdf-thumb-item.active{border-color:var(--lime)}
.pdf-thumb-item canvas{width:100%;border-radius:3px;display:block}
.pdf-thumb-num{font:400 .6rem 'Space Mono';color:var(--muted)}
.pdf-thumb-item.active .pdf-thumb-num{color:var(--lime)}
.pdf-viewer-area{flex:1;display:flex;flex-direction:column;overflow:hidden}
.pdf-toolbar{background:var(--panel2);border-bottom:1px solid var(--border);padding:10px 16px;display:flex;align-items:center;gap:12px;flex-shrink:0;flex-wrap:wrap}
.pdf-toolbar-group{display:flex;align-items:center;gap:7px}
.pdf-filename{font:400 .7rem 'Space Mono';color:var(--text);background:rgba(255,255,255,.05);border:1px solid var(--border);border-radius:6px;padding:5px 12px;letter-spacing:.03em}
.pdf-nav-btn{background:rgba(255,255,255,.06);border:1px solid var(--border);color:var(--text);width:28px;height:28px;border-radius:6px;cursor:pointer;display:flex;align-items:center;justify-content:center}
.pdf-nav-btn:hover:not(:disabled){background:var(--teal)}
.pdf-nav-btn:disabled{opacity:.3;cursor:not-allowed}
.pdf-page-info{font:400 .68rem 'Space Mono';color:var(--muted);display:flex;align-items:center;gap:5px}
.pdf-page-input{background:rgba(255,255,255,.06);border:1px solid var(--border);color:var(--text);font:400 .68rem 'Space Mono';text-align:center;width:36px;height:26px;border-radius:5px}
.pdf-zoom-btn{background:rgba(255,255,255,.06);border:1px solid var(--border);color:var(--text);height:26px;padding:0 10px;border-radius:6px;cursor:pointer;font:400 .66rem 'Space Mono'}
.pdf-zoom-btn:hover{background:rgba(255,255,255,.12)}
.pdf-zoom-level{font:400 .66rem 'Space Mono';color:var(--muted);min-width:36px;text-align:center}
.toolbar-sep{width:1px;height:18px;background:var(--border);margin:0 2px}
.pdf-canvas-area{flex:1;overflow:auto;display:flex;align-items:flex-start;justify-content:center;padding:22px;background:var(--dark)}
#pdf-main-canvas{border-radius:6px;box-shadow:0 8px 40px rgba(0,0,0,.6);display:block;background:#fff;max-width:100%}
.pdf-loading{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;color:var(--muted);font:400 .74rem 'Space Mono';height:100%;width:100%}
.pdf-spinner{width:34px;height:34px;border:3px solid rgba(77,124,138,.25);border-top-color:var(--lime);border-radius:50%;animation:spin .8s linear infinite}
@keyframes spin{to{transform:rotate(360deg)}}
.pdf-modal-footer{background:var(--panel2);border-top:1px solid var(--border);padding:13px 20px;display:flex;gap:10px;align-items:center;flex-shrink:0}
.pdf-footer-info{flex:1;font:400 .64rem 'Space Mono';color:var(--muted)}
.btn-fullscreen,.btn-download-modal{display:inline-flex;align-items:center;gap:7px;padding:9px 18px;border:none;color:#fff;border-radius:8px;font:600 .78rem Sora;cursor:pointer;text-decoration:none}
.btn-fullscreen{background:linear-gradient(135deg,var(--teal),var(--sage))}
.btn-download-modal{background:linear-gradient(135deg,var(--blue),var(--teal))}
.btn-fullscreen:hover,.btn-download-modal:hover{filter:brightness(1.12)}
@media(max-width:700px){.pdf-sidebar{display:none}.pdf-modal{height:94vh}}
</style></head><body>
<section id="login-screen"><div class="login-card"><div class="login-bar"><span class="dot red"></span><span class="dot yellow"></span><span class="dot green"></span><b>acceso.base_datos</b></div><div class="login-body"><div class="login-icon">⌘</div><h1 class="login-title">Acceso al Portafolio</h1><p class="login-sub">Matias Saforas Gomez · UPLA</p><form class="login-form" id="login-form"><div><label for="user">Usuario</label><input id="user" autocomplete="off" required></div><div><label for="pass">Contraseña</label><input id="pass" type="password" required></div><button class="login-submit">Ingresar</button><div class="login-error" id="login-error">Usuario o contraseña incorrectos.</div></form><p class="hint">Usuario: <b>M@t_SF</b> · Contraseña: <b>77222987</b></p><p class="login-foot">Portafolio académico · Base de Datos II</p></div></div></section>
<div id="app-screen"><nav><div class="nav-brand">Matias Saforas Gomez<br>Base de Datos II</div><ul class="nav-links"><li><a href="#perfil">Perfil</a></li><li><a href="#grimorio">Grimorio</a></li><li><a href="#unidades">Unidades</a></li><li><button id="logout-btn" class="logout">Salir</button></li></ul></nav>
<header class="hero" id="perfil"><div class="hero-inner"><p class="eyebrow">Universidad Peruana Los Andes · 2026-I</p><h1 class="hero-name">Matias<br><span>Saforas Gomez</span></h1><p class="hero-desc"><strong>Ingeniero de Sistemas en formación.</strong> Me interesa el desarrollo de soluciones tecnológicas, la gestión de bases de datos y la construcción de sistemas útiles, seguros y eficientes. Este portafolio reúne mi aprendizaje y evolución profesional.</p><div class="profile-grid"><div><small>Curso</small><strong>Base de Datos II (332151)</strong></div><div><small>Docente</small><strong>Mg. Raúl Enrique Fernández Bejarano</strong></div><div><small>Sede</small><strong>Huancayo, Perú</strong></div><div><small>Enfoque</small><strong>Gestión de bases de datos</strong></div><div><small>Especialidad</small><strong>Desarrollo de software</strong></div><div><small>Rol</small><strong>Administrador</strong></div></div></div></header>
<main><section id="grimorio"><p class="section-label">Ruta de aprendizaje</p><h2 class="section-title">Grimorio del Saber</h2><div class="codex-grid"><article class="codex-card"><span>01</span><h3>Dato</h3><p>Un hecho o fenómeno concreto que decidimos registrar, sin interpretar todavía.</p></article>
<article class="codex-card"><span>02</span><h3>Información</h3><p>El dato al que se le añade un significado dentro de un contexto.</p></article>
<article class="codex-card"><span>03</span><h3>Conocimiento</h3><p>Información combinada con experiencia, lista para explicar o predecir.</p></article>
<article class="codex-card"><span>04</span><h3>Sabiduría</h3><p>Conocimiento aplicado con criterio propio a la hora de decidir.</p></article></div></section>
<section id="unidades"><div class="inner"><p class="section-label">Registro académico</p><h2 class="section-title">Unidades del curso</h2><div class="unit-tabs"><button class="unit-tab active" data-target="unidad-1">Unidad I · Arquitecturas</button><button class="unit-tab locked" data-target="unidad-2">Unidad II · Instancias</button><button class="unit-tab locked" data-target="unidad-3">Unidad III · Seguridad</button><button class="unit-tab locked" data-target="unidad-4">Unidad IV · Monitoreo</button></div><div class="unit-panel active" id="unidad-1"><div class="capacity"><b>Capacidad:</b> reconocer las arquitecturas de bases de datos y su implementación en gestores DBMS vigentes para almacenar, organizar e integrar información.</div><div class="weeks-grid"><article class="week-card"><span class="week-num">Semana 01</span><h3>Formulación del proyecto y selección de la arquitectura</h3><p>Definir el alcance de un proyecto analítico a partir de un caso empresarial real, eligiendo y sustentando el tipo de arquitectura de base de datos (centralizada, distribuida o en la nube) que mejor responde a las necesidades de almacenamiento del negocio.</p><div class="card-pdf-thumb" onclick="openPDF('pdf/semana1.pdf','SEMANA1.pdf','Formulación del proyecto','Semana 01')"><div class="thumb-placeholder"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="15" y2="17"/></svg>Clic para ver</div></div><div class="card-actions"><button class="preview-btn" onclick="event.stopPropagation();openPDF('pdf/semana1.pdf','SEMANA1.pdf','Formulación del proyecto','Semana 01')"><svg viewBox="0 0 24 24"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>Ver PDF</button><a class="download-btn" href="pdf/semana1.pdf" download onclick="event.stopPropagation()"><svg viewBox="0 0 24 24"><path d="M12 16l-5-5h3V4h4v7h3l-5 5zm-7 2h14v2H5v-2z"/></svg></a></div><div class="progress"><i style="width:6.25%"></i></div><small>6.25% de avance acumulado</small><button class="questions-btn" onclick="toggleQuestions()">📝 Ver las 32 preguntas</button></article>
<article class="week-card"><span class="week-num">Semana 02</span><h3>Despliegue y configuración de motores de datos (DBMS)</h3><p>Instalar y configurar el sistema gestor de base de datos elegido para el proyecto, comprobando la conectividad y dejando listos los recursos iniciales del servidor.</p><div class="card-pdf-thumb" onclick="openPDF('pdf/semana2.pdf','SEMANA2.pdf','Despliegue de motores de datos','Semana 02')"><div class="thumb-placeholder"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="15" y2="17"/></svg>Clic para ver</div></div><div class="card-actions"><button class="preview-btn" onclick="event.stopPropagation();openPDF('pdf/semana2.pdf','SEMANA2.pdf','Despliegue de motores de datos','Semana 02')"><svg viewBox="0 0 24 24"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>Ver PDF</button><a class="download-btn" href="pdf/semana2.pdf" download onclick="event.stopPropagation()"><svg viewBox="0 0 24 24"><path d="M12 16l-5-5h3V4h4v7h3l-5 5zm-7 2h14v2H5v-2z"/></svg></a></div><div class="progress"><i style="width:12.5%"></i></div><small>12.50% de avance acumulado</small></article>
<article class="week-card"><span class="week-num">Semana 03</span><h3>Modelamiento físico y mecanismos de integración</h3><p>Estructurar e implementar los esquemas y las tablas maestras dentro del DBMS, configurando las restricciones necesarias para que el almacenamiento y la integración de datos masivos sean eficientes.</p><div class="card-pdf-thumb" onclick="openPDF('pdf/semana3.pdf','SEMANA3.pdf','Modelamiento físico e integración','Semana 03')"><div class="thumb-placeholder"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="15" y2="17"/></svg>Clic para ver</div></div><div class="card-actions"><button class="preview-btn" onclick="event.stopPropagation();openPDF('pdf/semana3.pdf','SEMANA3.pdf','Modelamiento físico e integración','Semana 03')"><svg viewBox="0 0 24 24"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>Ver PDF</button><a class="download-btn" href="pdf/semana3.pdf" download onclick="event.stopPropagation()"><svg viewBox="0 0 24 24"><path d="M12 16l-5-5h3V4h4v7h3l-5 5zm-7 2h14v2H5v-2z"/></svg></a></div><div class="progress"><i style="width:18.75%"></i></div><small>18.75% de avance acumulado</small></article>
<article class="week-card"><span class="week-num">Semana 04</span><h3>Sustentación y validación de la infraestructura de datos</h3><p>Sustentar el primer avance del proyecto mediante un informe técnico y una demostración en vivo, comprobando que el diseño de la arquitectura y la carga inicial de datos cumplen con los criterios de rendimiento e integración planteados. Cierra con el ingreso de notas al sistema.</p><div class="card-pdf-thumb" onclick="openPDF('pdf/semana4.pdf','SEMANA4.pdf','Sustentación y validación','Semana 04')"><div class="thumb-placeholder"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="15" y2="17"/></svg>Clic para ver</div></div><div class="card-actions"><button class="preview-btn" onclick="event.stopPropagation();openPDF('pdf/semana4.pdf','SEMANA4.pdf','Sustentación y validación','Semana 04')"><svg viewBox="0 0 24 24"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>Ver PDF</button><a class="download-btn" href="pdf/semana4.pdf" download onclick="event.stopPropagation()"><svg viewBox="0 0 24 24"><path d="M12 16l-5-5h3V4h4v7h3l-5 5zm-7 2h14v2H5v-2z"/></svg></a></div><div class="progress"><i style="width:25.0%"></i></div><small>25.00% de avance acumulado</small></article></div><div class="questions-panel" id="questionsPanel"><div class="questions-panel-head"><div><h3>32 preguntas de Base de Datos</h3><span>Evaluación asociada a la Semana 01</span></div><button class="questions-close" onclick="toggleQuestions()">Cerrar ✕</button></div><div class="questions-grid"><article class="question-card" id="pregunta-01"><span class="q-number">01</span><div><h3>Base de datos utilizada</h3><p>Una base de datos que he utilizado como consumidor es la de un sistema académico universitario. Puede contener entidades como Estudiante, Curso, Docente, Matrícula, Sección y Calificación. Por ejemplo, un estudiante se matricula en varios cursos y cada matrícula se relaciona con sus calificaciones.</p></div></article>
<article class="question-card" id="pregunta-02"><span class="q-number">02</span><div><h3>Grupos de usuarios</h3><p>Los principales grupos de usuarios pueden ser estudiantes, docentes, personal administrativo, coordinadores académicos y administradores de la base de datos. Cada grupo utiliza la información según sus funciones y permisos.</p></div></article>
<article class="question-card" id="pregunta-03"><span class="q-number">03</span><div><h3>Aplicación de un grupo de usuarios</h3><p>Para los estudiantes, una aplicación puede ser el portal académico. Permite consultar cursos matriculados, horarios y calificaciones mediante formularios y reportes.</p></div></article>
<article class="question-card" id="pregunta-04"><span class="q-number">04</span><div><h3>Persistencia</h3><p>La persistencia significa que los datos permanecen almacenados después de terminar una sesión o apagar el sistema. La información queda disponible para futuras consultas y operaciones.</p></div></article>
<article class="question-card" id="pregunta-05"><span class="q-number">05</span><div><h3>Interrelación</h3><p>La interrelación significa que los datos están relacionados entre sí. Por ejemplo, un estudiante se relaciona con sus matrículas, cursos y calificaciones, permitiendo consultar información conectada.</p></div></article>
<article class="question-card" id="pregunta-06"><span class="q-number">06</span><div><h3>Compartir</h3><p>Compartir significa que diferentes usuarios o áreas pueden utilizar los mismos datos de una base de datos de acuerdo con sus permisos. Esto evita duplicaciones y facilita trabajar con información común y actualizada.</p></div></article>
<article class="question-card" id="pregunta-07"><span class="q-number">07</span><div><h3>¿Qué es un DBMS?</h3><p>Un DBMS o sistema de administración de bases de datos es el software que permite definir, almacenar, consultar, actualizar y administrar una base de datos. También ayuda a controlar el acceso y el procesamiento de transacciones.</p></div></article>
<article class="question-card" id="pregunta-08"><span class="q-number">08</span><div><h3>Acceso procedural y no procedural</h3><p>El acceso procedural indica cómo realizar paso a paso las operaciones para obtener los datos. El acceso no procedural indica qué datos se necesitan sin detallar cada paso de acceso. La principal diferencia es que el segundo deja al DBMS decidir cómo ejecutar la consulta.</p></div></article>
<article class="question-card" id="pregunta-09"><span class="q-number">09</span><div><h3>Importancia del acceso no procedural</h3><p>El acceso no procedural es importante porque permite obtener información sin escribir código detallado para recorrer los datos. Esto mejora la productividad del software y facilita el desarrollo y mantenimiento de aplicaciones.</p></div></article>
<article class="question-card" id="pregunta-10"><span class="q-number">10</span><div><h3>Acceso no procedural y productividad</h3><p>La conexión es directa: formularios y reportes pueden especificar los requerimientos de datos mediante consultas, mientras el DBMS se encarga de encontrar y recuperar la información. Por ello, el acceso no procedural puede reducir código y facilitar el desarrollo de aplicaciones.</p></div></article>
<article class="question-card" id="pregunta-11"><span class="q-number">11</span><div><h3>Formulario y reporte</h3><p>Un formulario está orientado principalmente a ingresar, modificar o consultar información de manera interactiva. Un reporte presenta información organizada para lectura, análisis, impresión o toma de decisiones.</p></div></article>
<article class="question-card" id="pregunta-12"><span class="q-number">12</span><div><h3>Interfaz de lenguaje procedural</h3><p>Es el mecanismo que permite combinar el acceso no procedural a una base de datos con un lenguaje de programación procedural, como COBOL o Visual Basic. Así, una aplicación puede ejecutar consultas y operaciones de la base de datos dentro de un programa.</p></div></article>
<article class="question-card" id="pregunta-13"><span class="q-number">13</span><div><h3>Transacción</h3><p>Una transacción es una unidad de trabajo que debe procesarse de forma completa y confiable. Por ejemplo, registrar una matrícula puede implicar varias operaciones que deben quedar correctamente realizadas para conservar la consistencia.</p></div></article>
<article class="question-card" id="pregunta-14"><span class="q-number">14</span><div><h3>Funciones del DBMS para transacciones</h3><p>El DBMS proporciona funciones para controlar transacciones, mantener la consistencia, manejar el acceso concurrente y recuperar la información cuando ocurre una falla. De esta manera, las operaciones se procesan de forma confiable.</p></div></article>
<article class="question-card" id="pregunta-15"><span class="q-number">15</span><div><h3>Transacción de la base de datos elegida</h3><p>Una transacción puede ser la matrícula de un estudiante en un curso. Se utiliza especialmente al inicio de cada periodo académico y puede ser enviada por muchos estudiantes al mismo tiempo. La cantidad exacta depende de la institución y de la carga del sistema.</p></div></article>
<article class="question-card" id="pregunta-16"><span class="q-number">16</span><div><h3>DBMS corporativo</h3><p>Es un DBMS diseñado para organizaciones y grandes bases de datos, con muchos usuarios simultáneos. Suele ejecutarse en servidores potentes y soporta procesamiento de transacciones, disponibilidad, seguridad y rendimiento.</p></div></article>
<article class="question-card" id="pregunta-17"><span class="q-number">17</span><div><h3>DBMS de escritorio</h3><p>Es un DBMS que se ejecuta normalmente en computadoras personales o servidores pequeños. Soporta un procesamiento más limitado y resulta apropiado para equipos de trabajo y negocios pequeños.</p></div></article>
<article class="question-card" id="pregunta-18"><span class="q-number">18</span><div><h3>DBMS embebido</h3><p>Es un DBMS que reside dentro de un sistema más grande, como una aplicación o dispositivo. Ofrece procesamiento transaccional limitado y requiere pocos recursos de memoria, procesamiento y almacenamiento.</p></div></article>
<article class="question-card" id="pregunta-19"><span class="q-number">19</span><div><h3>Funciones de la primera generación</h3><p>La primera generación se basaba principalmente en estructuras de archivos y acceso mediante programas. Permitía búsquedas secuenciales y aleatorias, pero el usuario necesitaba escribir programas para obtener la información y existía poco soporte para relacionar datos.</p></div></article>
<article class="question-card" id="pregunta-20"><span class="q-number">20</span><div><h3>Funciones de la segunda generación</h3><p>La segunda generación incorporó DBMS reales capaces de administrar muchas entidades y relaciones. Se caracterizó por el acceso navegacional, donde el programador debía escribir código para navegar entre registros relacionados; algunos productos utilizaron estándares como CODASYL.</p></div></article>
<article class="question-card" id="pregunta-21"><span class="q-number">21</span><div><h3>Funciones de la tercera generación</h3><p>La tercera generación se caracterizó por los DBMS relacionales y los lenguajes no procedurales. El acceso mediante relaciones y operadores, junto con la optimización de tecnología, permitió consultar datos de manera más flexible y eficiente.</p></div></article>
<article class="question-card" id="pregunta-22"><span class="q-number">22</span><div><h3>Funciones de la cuarta generación</h3><p>La cuarta generación incorporó capacidades orientadas a objetos y soportó funciones como multimedia, procesamiento distribuido, operadores más poderosos y procesamiento de datos para data warehouse, además de nuevas posibilidades de integración.</p></div></article>
<article class="question-card" id="pregunta-23"><span class="q-number">23</span><div><h3>Tres niveles del esquema</h3><p>Nivel externo: presenta las vistas de información que necesita cada tipo de usuario. Nivel conceptual: representa la estructura lógica global de entidades, atributos y relaciones. Nivel interno: describe cómo se almacenan físicamente los datos, incluyendo estructuras e índices.</p></div></article>
<article class="question-card" id="pregunta-24"><span class="q-number">24</span><div><h3>Propósito del mapeo</h3><p>El mapeo relaciona los niveles externo, conceptual e interno y permite transformar una vista de usuario en la representación lógica y luego en la forma de almacenamiento. El DBMS es responsable de realizar y administrar estos mapeos.</p></div></article>
<article class="question-card" id="pregunta-25"><span class="q-number">25</span><div><h3>Arquitectura de tres esquemas e independencia</h3><p>La separación entre los niveles permite cambiar detalles de un nivel sin modificar necesariamente los otros. Por ejemplo, cambiar la forma física de almacenamiento puede hacerse sin cambiar las vistas de los usuarios. Esto reduce los costos de mantenimiento del software.</p></div></article>
<article class="question-card" id="pregunta-26"><span class="q-number">26</span><div><h3>Interacción de usuarios con la base de datos</h3><p>Los usuarios funcionales activos interactúan directamente con formularios, consultas y reportes. Los usuarios pueden trabajar con vistas externas de la información según sus necesidades, mientras el DBMS gestiona el acceso a los datos.</p></div></article>
<article class="question-card" id="pregunta-27"><span class="q-number">27</span><div><h3>Cliente-servidor y división del procesamiento</h3><p>El procesamiento se divide para aprovechar las capacidades del cliente y del servidor. El cliente puede manejar la interfaz y parte de la lógica, mientras el servidor administra los datos y las operaciones del DBMS. El servidor no hace todo porque distribuir la carga puede mejorar el uso de recursos y la respuesta.</p></div></article>
<article class="question-card" id="pregunta-28"><span class="q-number">28</span><div><h3>Datos en varias computadoras</h3><p>En una arquitectura cliente-servidor o distribuida, los datos pueden almacenarse en varias computadoras para repartir la carga, acercar la información a diferentes ubicaciones, mejorar el rendimiento y aumentar la disponibilidad del sistema.</p></div></article>
<article class="question-card" id="pregunta-29"><span class="q-number">29</span><div><h3>Usuarios indirectos, paramétricos y poderosos</h3><p>Los usuarios indirectos reciben información mediante reportes preparados. Los usuarios paramétricos utilizan formularios o consultas con parámetros definidos, por ejemplo, seleccionando un curso o periodo. Los usuarios poderosos o experimentados realizan consultas más flexibles y pueden crear o adaptar formularios y reportes.</p></div></article>
<article class="question-card" id="pregunta-30"><span class="q-number">30</span><div><h3>Usuario funcional activo y analista</h3><p>El usuario funcional activo trabaja directamente con la información mediante las aplicaciones de la organización. El analista estudia requerimientos, diseña soluciones y participa en el desarrollo de sistemas. Ambos utilizan principalmente el nivel externo para entender las necesidades, mientras el analista también debe considerar la estructura conceptual.</p></div></article>
<article class="question-card" id="pregunta-31"><span class="q-number">31</span><div><h3>Objetivo profesional</h3><p>Como objetivo a largo plazo elegiría ser administrador de bases de datos, porque me interesa la tecnología, la gestión de información y el funcionamiento de los sistemas. Este puesto me permitiría trabajar en seguridad, rendimiento, disponibilidad y administración de bases de datos.</p></div></article>
<article class="question-card" id="pregunta-32"><span class="q-number">32</span><div><h3>Nicho de los DBMS de código libre</h3><p>Los DBMS de código libre ocupan un espacio importante en proyectos educativos, emprendimientos, organizaciones y empresas que buscan reducir costos de licenciamiento y contar con soluciones flexibles. También son útiles para desarrolladores y equipos que necesitan adaptar la tecnología a sus necesidades.</p></div></article></div></div></div><div class="unit-panel" id="unidad-2"><div class="capacity">Unidad reservada para instancias, almacenamiento y datos masivos.</div></div><div class="unit-panel" id="unidad-3"><div class="capacity">Unidad reservada para seguridad, red y alta disponibilidad.</div></div><div class="unit-panel" id="unidad-4"><div class="capacity">Unidad reservada para monitoreo, desempeño y flashback.</div></div></div></section>
</main>
<footer>Matias Saforas Gomez · Facultad de Ingeniería de Sistemas y Computación · Universidad Peruana Los Andes</footer></div>
<button class="bot-toggle" id="bot-toggle" aria-label="Abrir asistente">✦</button><aside class="bot-panel" id="bot-panel"><div class="bot-head"><strong>Asistente del portafolio</strong><button id="bot-close" class="logout">×</button></div><div class="bot-messages" id="bot-messages"><div class="msg">Hola. Pregúntame por Matias, el curso, las unidades o las preguntas finales.</div></div><form class="bot-form" id="bot-form"><input id="bot-input" placeholder="Escribe una pregunta…"><button>↑</button></form></aside>
<div class="pdf-modal-overlay" id="pdfModalOverlay" onclick="closePDFonOverlay(event)"><div class="pdf-modal"><div class="pdf-modal-header"><span style="font-size:1.2rem;">📁</span><div><div class="pdf-modal-folder" id="modalTitle">Documento</div><div class="pdf-modal-subtitle">Lea el pdf directamente aquí abajo:</div></div><button class="pdf-modal-close" onclick="closePDF()">✕</button></div><div class="pdf-modal-body"><div class="pdf-sidebar" id="pdfSidebar"></div><div class="pdf-viewer-area"><div class="pdf-toolbar"><div class="pdf-filename" id="pdfFilename">SEMANA.pdf</div><div class="toolbar-sep"></div><div class="pdf-toolbar-group"><button class="pdf-nav-btn" id="btnPrev" onclick="changePage(-1)" title="Anterior">‹</button><div class="pdf-page-info"><input class="pdf-page-input" id="pageInput" type="number" min="1" value="1" onchange="jumpToPage(this.value)"><span>/ <span id="totalPages">?</span></span></div><button class="pdf-nav-btn" id="btnNext" onclick="changePage(1)" title="Siguiente">›</button></div><div class="toolbar-sep"></div><div class="pdf-toolbar-group"><button class="pdf-zoom-btn" onclick="changeZoom(-0.15)">− Zoom</button><span class="pdf-zoom-level" id="zoomLevel">93%</span><button class="pdf-zoom-btn" onclick="changeZoom(0.15)">+ Zoom</button></div></div><div class="pdf-canvas-area" id="pdfCanvasArea"><div class="pdf-loading" id="pdfLoading"><div class="pdf-spinner"></div><span>Cargando PDF...</span></div><canvas id="pdf-main-canvas" style="display:none;"></canvas></div></div></div><div class="pdf-modal-footer"><div class="pdf-footer-info" id="footerInfo">Listo para visualizar</div><button class="btn-fullscreen" onclick="openFullscreen()">🖥 Pantalla completa</button><a class="btn-download-modal" id="btnDownload" href="#" download>💾 Descargar</a></div></div></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
<script>
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
let pdfDoc=null,currentPage=1,totalPages=0,scale=0.93,currentPdfUrl='';
function openPDF(url,filename,title,subtitle){
  currentPdfUrl=url;
  document.getElementById('modalTitle').textContent=title;
  document.getElementById('pdfFilename').textContent=filename;
  document.getElementById('btnDownload').href=url;
  document.getElementById('btnDownload').download=filename;
  document.getElementById('footerInfo').textContent=subtitle+' · '+filename;
  const overlay=document.getElementById('pdfModalOverlay');
  overlay.classList.add('open');
  document.body.style.overflow='hidden';
  pdfDoc=null;currentPage=1;
  document.getElementById('pdfLoading').style.display='flex';
  document.getElementById('pdfLoading').innerHTML='<div class="pdf-spinner"></div><span>Cargando PDF...</span>';
  document.getElementById('pdf-main-canvas').style.display='none';
  document.getElementById('pdfSidebar').innerHTML='';
  document.getElementById('totalPages').textContent='?';
  document.getElementById('pageInput').value=1;
  document.getElementById('zoomLevel').textContent=Math.round(scale*100)+'%';
  pdfjsLib.getDocument(url).promise.then(function(pdf){
    pdfDoc=pdf;totalPages=pdf.numPages;
    document.getElementById('totalPages').textContent=totalPages;
    document.getElementById('pageInput').max=totalPages;
    renderPage(1);renderAllThumbs();
  }).catch(function(err){
    document.getElementById('pdfLoading').innerHTML='<span style="color:var(--danger);font-family:Space Mono,monospace;font-size:.78rem;">⚠ No se pudo cargar el PDF.<br>Asegúrate de que el archivo existe en la carpeta <code>pdf/</code>.</span>';
  });
}
function closePDF(){document.getElementById('pdfModalOverlay').classList.remove('open');document.body.style.overflow='';}
function closePDFonOverlay(e){if(e.target===document.getElementById('pdfModalOverlay'))closePDF();}
function renderPage(num){
  if(!pdfDoc)return;
  pdfDoc.getPage(num).then(function(page){
    const canvas=document.getElementById('pdf-main-canvas'),ctx=canvas.getContext('2d');
    const viewport=page.getViewport({scale:scale});
    canvas.height=viewport.height;canvas.width=viewport.width;
    page.render({canvasContext:ctx,viewport:viewport}).promise.then(function(){
      document.getElementById('pdfLoading').style.display='none';
      canvas.style.display='block';
      currentPage=num;
      document.getElementById('pageInput').value=num;
      document.getElementById('btnPrev').disabled=num<=1;
      document.getElementById('btnNext').disabled=num>=totalPages;
      highlightThumb(num);
    });
  });
}
function renderAllThumbs(){
  const sidebar=document.getElementById('pdfSidebar');sidebar.innerHTML='';
  for(let i=1;i<=totalPages;i++){(function(pageNum){
    const item=document.createElement('div');
    item.className='pdf-thumb-item'+(pageNum===1?' active':'');
    item.id='thumb-'+pageNum;
    item.onclick=function(){renderPage(pageNum);};
    const thumbCanvas=document.createElement('canvas');
    const numLabel=document.createElement('div');
    numLabel.className='pdf-thumb-num';numLabel.textContent=pageNum;
    item.appendChild(thumbCanvas);item.appendChild(numLabel);sidebar.appendChild(item);
    pdfDoc.getPage(pageNum).then(function(page){
      const viewport=page.getViewport({scale:0.28});
      thumbCanvas.width=viewport.width;thumbCanvas.height=viewport.height;
      page.render({canvasContext:thumbCanvas.getContext('2d'),viewport:viewport});
    });
  })(i);}
}
function highlightThumb(num){
  document.querySelectorAll('.pdf-thumb-item').forEach(t=>t.classList.remove('active'));
  const th=document.getElementById('thumb-'+num);
  if(th){th.classList.add('active');th.scrollIntoView({block:'nearest',behavior:'smooth'});}
}
function changePage(delta){const n=currentPage+delta;if(n>=1&&n<=totalPages)renderPage(n);}
function jumpToPage(val){const n=parseInt(val);if(n>=1&&n<=totalPages)renderPage(n);}
function changeZoom(delta){scale=Math.max(0.4,Math.min(2.5,scale+delta));document.getElementById('zoomLevel').textContent=Math.round(scale*100)+'%';renderPage(currentPage);}
function openFullscreen(){if(currentPdfUrl)window.open(currentPdfUrl,'_blank');}
document.addEventListener('keydown',function(e){
  if(!document.getElementById('pdfModalOverlay').classList.contains('open'))return;
  if(e.key==='Escape')closePDF();
  if(e.key==='ArrowRight'||e.key==='ArrowDown')changePage(1);
  if(e.key==='ArrowLeft'||e.key==='ArrowUp')changePage(-1);
});
function toggleQuestions(){
  const panel=document.getElementById('questionsPanel');
  panel.classList.toggle('open');
  if(panel.classList.contains('open'))panel.scrollIntoView({behavior:'smooth',block:'start'});
}
</script>
<script>
const login=document.getElementById('login-screen'),app=document.getElementById('app-screen'),error=document.getElementById('login-error');document.getElementById('login-form').addEventListener('submit',e=>{e.preventDefault();if(user.value.trim()==='M@t_SF'&&pass.value==='77222987'){login.style.display='none';app.style.display='block';error.style.display='none';window.scrollTo(0,0)}else error.style.display='block'});document.getElementById('logout-btn').onclick=()=>{app.style.display='none';login.style.display='grid';pass.value='';window.scrollTo(0,0)};
document.querySelectorAll('.unit-tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.unit-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.unit-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.target).classList.add('active')});
const bp=document.getElementById('bot-panel');document.getElementById('bot-toggle').onclick=()=>bp.classList.toggle('open');document.getElementById('bot-close').onclick=()=>bp.classList.remove('open');document.getElementById('bot-form').addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('bot-input'),text=input.value.trim();if(!text)return;const box=document.getElementById('bot-messages');box.insertAdjacentHTML('beforeend','<div class="msg">'+text.replace(/[<>]/g,'')+'</div>');let r='Puedes revisar el perfil, el Grimorio o las unidades del curso.';const q=text.toLowerCase();if(q.includes('matias')||q.includes('michael'))r='Matias Saforas Gomez es estudiante de Ingeniería de Sistemas en la UPLA.';else if(q.includes('curso'))r='El curso es Base de Datos II (332151), semestre 2026-I.';else if(q.includes('docente'))r='El docente es el Mg. Raúl Enrique Fernández Bejarano.';else if(q.includes('pregunta'))r='Las 32 preguntas están dentro de la tarjeta de la Semana 01, en la sección Unidades.';box.insertAdjacentHTML('beforeend','<div class="msg">'+r+'</div>');input.value='';box.scrollTop=box.scrollHeight});
</script></body></html>
